version: "3.8"

services:
  db:
    image: mongo:4.4.1
    restart: unless-stopped
    container_name: db
    env_file: .env
    environment:
    - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
    - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    - MONGO_INITDB_DATABASE=$MONGO_HOSTNAME
    ports:
    - "27017:27017"
    networks:
    - app-network  

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: web
    env_file: .env
    environment:
    - NODE_ENV=production
    - NODE_PORT=8080
    - MONGO_USERNAME=$MONGO_USERNAME
    - MONGO_PASSWORD=$MONGO_PASSWORD
    - MONGO_HOSTNAME=$MONGO_HOSTNAME
    - MONGO_PORT=$MONGO_PORT
    - MONGO_DB=$MONGO_DB 
    ports:
    - "8080:8080"
    networks:
    - app-network
    depends_on:
    - db
  
  nginx:
    image: nginx:1.19.3
    restart: unless-stopped
    container_name: nginx
    volumes:
    - ./assets/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    networks:
    - app-network
    depends_on:
    - web

networks:
  app-network:
    driver: bridge
